#ifndef TIMER1_config_H
#define TIMER1_config_H

/* TIMER1_FAST_PWM_ICR
	TIMER1_FAST_PWM
*/
#define TIMER1_MODE		 TIMER1_FAST_PWM_ICR


#define TIMER1_PRESCALER  TIMER1_DIV_BY_64

/* TIMER1_INVERTED
   TIMER1_NON_INVERTED
*/
#define TIMER1_COM_EVENT  TIMER1_INVERTED

#endif